data:
  dataset: noisy_cifar3
  noise_rate: 0.2
  class_type: animal

model:
  architecture: resnet18
  num_classes: 3

wandb:
  mode: online # "disabled" or "online"
  entity: siit-iitp
  project: noisy-label
  name: NoisyCIFAR3(symm,0.2,animal)-CE
  save_code: true

trainer:
  optimizer: sgd
  init_lr: 1.0e-1
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_scheduler: multistep
  max_epoch: 200
  loss_fn: cross_entropy
  num_workers: 2
  batch_size: 128
  save_model: true
