data:
  dataset: noisy_cifar100
  noise_rate: 0.2
  noise_type: asymmetric
  random_seed: 42
  download: true

model:
  architecture: resnet18
  num_classes: 100

wandb:
  mode: online # "disabled" or "online"
  # entity: siit-iitp
  entity: seunghee1215
  project: noisy-label
  name: NoisyCIFAR100(asymm,0.2)-CE
  save_code: true

trainer:
  optimizer: sgd
  init_lr: 1.0e-1
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_scheduler: multistep
  max_epoch: 200
  loss_fn: cross_entropy
  num_workers: 2
  batch_size: 128
  save_model: true
