method: nrd

data:
  dataset: webvision

model:
  architecture: resnet50_torchvision
  num_classes: 50
  pretrained: false

wandb:
  mode: online # "online" or "online"
  entity: hyounguk-shon
  project: noisy-label
  name: WebVision-CE-NRD
  save_code: true

trainer:
  enable_amp: true
  optimizer: sgd
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_scheduler: cosine
  max_epoch: 120
  num_workers: 10
  batch_size: 128
  save_model: true
  loss_fn: cross_entropy
  alpha: 0.5
  teacher_aug: autoaugment
  student_aug: randomcrop
  distill_loss_fn: cross_entropy
  temperature: 1.0