data:
  dataset: webvision

model:
  architecture: resnet50_torchvision
  num_classes: 50
  pretrained: true

wandb:
  mode: online # "disabled" or "online"
  entity: hyounguk-shon
  project: noisy-label
  name: WebVision-MAE
  save_code: true

trainer:
  enable_amp: true
  optimizer: sgd
  init_lr: 0.001
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_scheduler: cosine
  max_epoch: 40
  num_workers: 10
  batch_size: 128
  save_model: true
  loss_fn: mae