method: nrd

data:
  dataset: cifar100n
  download: true

model:
  architecture: resnet34
  num_classes: 100

wandb:
  mode: online # "disabled" or "online"
  entity: hyounguk-shon
  project: noisy-label
  name: table2-r34
  save_code: true

trainer:
  optimizer: sgd
  init_lr: 0.01
  momentum: 0.9
  weight_decay: 5.0e-4
  lr_scheduler: multistep
  max_epoch: 100
  num_workers: 4
  batch_size: 128
  save_model: false
  loss_fn: mae
  alpha: 0.5
  teacher_aug: autoaugment
  student_aug: randomcrop
  distill_loss_fn: smoothed_l1_dist
  temperature: 1.0
  enable_amp: false