data:
  dataset: cifar10n
  download: true

model:
  architecture: resnet18
  num_classes: 10

wandb:
  mode: online # "disabled" or "online"
  entity: hyounguk-shon
  project: noisy-label
  name: CIFAR10N-SCE
  save_code: true

trainer:
  optimizer: sgd
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_scheduler: multistep
  max_epoch: 200
  num_workers: 2
  batch_size: 128
  save_model: true
  loss_fn: symmetric_cross_entropy
  loss_param:
    alpha: 0.1
    beta: 1.0
  alpha: 0.5
  enable_amp: false
  aug: autoaugment