data:
  dataset: cifar10n
  noise_type: worse_label
  download: true

model:
  architecture: resnet18
  num_classes: 10

wandb:
  mode: online # "disabled" or "online"
  entity: hyounguk-shon
  project: noisy-label
  name: CIFAR10N(worse_label)-MAE
  save_code: true

trainer:
  optimizer: sgd
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_scheduler: multistep
  max_epoch: 200
  num_workers: 2
  batch_size: 128
  save_model: true
  loss_fn: mae
  enable_amp: false
  aug: autoaugment