data:
  dataset: noisy_cifar10
  noise_rate: 0.2
  noise_type: symmetric

model:
  architecture: resnet18
  num_classes: 10

wandb:
  mode: disabled # "disabled" or "online"
  project: noisy-label
  entity: noisy-label

trainer:
  optimizer: sgd
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  lr_scheduler: cosine
  max_epoch: 200
  loss_fn: cross_entropy
  num_workers: 0
  batch_size: 128
  save_model: True
