data:
  dataset: noisy_cifar100
  noise_rate: 0.1
  noise_type: asymmetric
  random_seed: 42
  download: true

model:
  architecture: resnet18
  num_classes: 100

wandb:
  mode: online # "disabled" or "online"
  entity: hyounguk-shon
  project: noisy-label
  name: NoisyCIFAR100(asymm,0.1)-MAE-NRD
  save_code: true

trainer:
  optimizer: sgd
  init_lr: 0.01
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_scheduler: multistep
  max_epoch: 200
  num_workers: 2
  batch_size: 128
  save_model: true
  loss_fn: mae
  alpha: 0.5
  teacher_aug: randomcrop
  student_aug: autoaugment
  distill_loss_fn: smoothed_l1_dist
  temperature: 1.0
  enable_amp: false