data:
  dataset: clothing1m

model:
  architecture: resnet50
  num_classes: 14

wandb:
  mode: online # "disabled" or "online"
  entity: siit-iitp
  project: noisy-label
  name: Clothing1M-CE
  save_code: true

trainer:
  enable_amp: true
  optimizer: sgd
  init_lr: 0.001
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_scheduler: cosine
  max_epoch: 40
  num_workers: 4
  batch_size: 128
  save_model: true
  loss_fn: cross_entropy