data:
  dataset: noisy_cifar100
  noise_rate: 0.2
  noise_type: symmetric
  random_seed: 42
  download: true

model:
  architecture: resnet18
  num_classes: 100

wandb:
  mode: online # "disabled" or "online"
  entity: hyounguk-shon
  project: noisy-label
  name: NoisyCIFAR100(symm,0.2)-SCE-NRD
  save_code: true

trainer:
  optimizer: sgd
  init_lr: 1.0e-1
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_scheduler: multistep
  max_epoch: 200
  loss_fn: symmetric_cross_entropy
  num_workers: 2
  batch_size: 128
  save_model: true
  enable_amp: false
  teacher_aug: randomcrop
  student_aug: autoaugment
  loss_param:
    alpha: 6.0
    beta: 0.1
  distill_loss_fn: smoothed_l1_dist
  temperature: 1.0
  alpha: 0.5
