method: vanilla

data:
  dataset: cifar10n
  noise_type: worse_label
  download: true

model:
  architecture: resnet34
  num_classes: 10

wandb:
  mode: online # "disabled" or "online"
  entity: hyounguk-shon
  project: noisy-label
  name: table2-r34
  save_code: true

trainer:
  optimizer: sgd
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 5.0e-4
  lr_scheduler: multistep
  max_epoch: 100
  num_workers: 4
  batch_size: 128
  save_model: false
  aug: randomcrop
  loss_fn: generalized_cross_entropy
  alpha: 0.5
  enable_amp: false
  loss_param:
    q: 0.7
