data:
  dataset: noisy_cifar100
  download: 'true'
  noise_rate: 0.5
  noise_type: symmetric
  random_seed: 42
model:
  architecture: resnet18
  num_classes: 100
trainer:
  batch_size: 128
  init_lr: 0.1
  loss_fn: generalized_cross_entropy
  loss_param:
    q: 0.7
  lr_scheduler: multistep
  max_epoch: 200
  momentum: 0.9
  num_workers: 2
  optimizer: sgd
  save_model: 'true'
  weight_decay: 0.0001
wandb:
  entity: seunghee1215
  mode: online
  name: NoisyCIFAR100(symm,0.5)-GCE
  project: noisy-label
  save_code: 'true'
